[package]
name = "buke"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
regex = { version = "1", optional = true }
nix = "*"

[features]
default = ["re"]
re = ["regex"]
